# Generated by Django 2.0.5 on 2018-05-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelManagers(
            name='candidate',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='professional',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
